/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------

unsigned int __fastcall COBSEncode(unsigned int result, unsigned __int8 **a2, unsigned __int8 **a3);
int __fastcall COBSDecode(int a1, unsigned __int8 **a2, const unsigned __int8 *a3, unsigned __int16 *a4);

//-------------------------------------------------------------------------
// Data declarations

int elf_hash_bucket[17] = { 0, 19, 23, 5, 0, 12, 0, 16, 6, 22, 13, 14, 0, 17, 11, 20, 0 }; // weak
int dword_868 = 0; // weak
int dword_1874 = 0; // weak
int (*unk_1950)(void) = &dword_0; // weak
void *off_1960 = &__register_frame_info; // weak
void *off_1964 = &Jv_RegisterClasses; // weak
void *off_1968 = &__cxa_finalize; // weak
void *off_196C = &__deregister_frame_info; // weak
void *_data_start = &_data_start; // weak
char byte_1974; // weak
_UNKNOWN unk_1978; // weak


//----- (00000454) --------------------------------------------------------
void init_proc()
{
  ;
}

//----- (0000045C) --------------------------------------------------------
int sub_45C()
{
  return unk_1950();
}
// 1950: using guessed type int (*unk_1950)(void);

//----- (00000494) --------------------------------------------------------
int btext()
{
  int result; // r0

  if ( !byte_1974 )
  {
    if ( off_1968 )
      result = _cxa_finalize(_data_start);
    if ( off_196C )
      result = _deregister_frame_info(&dword_868);
    byte_1974 = 1;
  }
  return result;
}
// 488: using guessed type int __fastcall _deregister_frame_info(_DWORD);
// 868: using guessed type int dword_868;
// 1968: using guessed type void *off_1968;
// 196C: using guessed type void *off_196C;
// 1970: using guessed type void *_data_start;
// 1974: using guessed type char byte_1974;

//----- (00000510) --------------------------------------------------------
int *sub_510()
{
  int *result; // r0

  if ( off_1960 )
    _register_frame_info(&dword_868, &unk_1978);
  result = &dword_1874;
  if ( dword_1874 )
  {
    if ( off_1964 )
      return (int *)((int (__fastcall *)(int *))off_1964)(&dword_1874);
  }
  return result;
}
// 470: using guessed type int __fastcall _register_frame_info(_DWORD, _DWORD);
// 868: using guessed type int dword_868;
// 1874: using guessed type int dword_1874;
// 1960: using guessed type void *off_1960;
// 1964: using guessed type void *off_1964;
// 19A0: using guessed type int __fastcall Jv_RegisterClasses(_DWORD);

//----- (00000588) --------------------------------------------------------
unsigned int __fastcall COBSEncode(unsigned int result, unsigned __int8 **a2, unsigned __int8 **a3)
{
  unsigned __int8 *v3; // r12
  unsigned __int8 *v4; // r3
  bool v5; // cc
  unsigned int v6; // r4
  char v7; // r5
  unsigned __int8 *v8; // r5
  bool v9; // zf
  bool v10; // cc
  _BYTE *v11; // r5

  v3 = *a2;
  if ( !a3 )
    goto LABEL_33;
  v4 = *a3;
  v5 = *a3 != 0;
  if ( *a3 )
    v5 = v3 > v4;
  if ( v5 )
  {
    v6 = *v4;
    v7 = *v4;
  }
  else
  {
LABEL_33:
    v7 = 1;
    v4 = *a2;
    v6 = 1;
    ++v3;
  }
  if ( !result )
  {
    v8 = (unsigned __int8 *)(v7 & 0xF0);
    v9 = v6 == 0xDE;
    if ( v6 <= 0xDE )
      v9 = v8 == (unsigned __int8 *)&elf_hash_bucket[5];
    if ( v9 )
    {
      v8 = v3;
      LOBYTE(v6) = v6 + 1;
    }
    else if ( v6 == 0xE0 )
    {
      v8 = v3;
      LOBYTE(v6) = 0xD3;
    }
    else
    {
      v10 = v6 > 0x1F;
      if ( v6 <= 0x1F )
      {
        LOBYTE(v6) = v6 - 0x21;
        v8 = v3;
      }
      else
      {
        *v4 = v6;
      }
      if ( v10 )
      {
        v4 = v3;
        v8 = v3 + 1;
      }
      if ( v10 )
        LOBYTE(v6) = 1;
    }
    goto LABEL_21;
  }
  if ( (v7 & 0xE0) == 0xE0 )
  {
    v11 = v3 + 1;
    *v4 = v6 + 0x21;
LABEL_34:
    v4 = v3;
    LOBYTE(v6) = 2;
    *v11 = result;
    v8 = v11 + 1;
    goto LABEL_21;
  }
  if ( v6 == 0xD3 )
  {
    v11 = v3 + 1;
    *v4 = 0xE0;
    goto LABEL_34;
  }
  if ( (v7 & 0xF0) == 0xD0 )    // 0xDD
  {
    v11 = v3 + 1;
    *v4 = v6 - 1;
    goto LABEL_34;
  }
  v6 = (unsigned __int8)(v6 + 1);
  *v3 = result;
  v8 = v3 + 1;
  if ( v6 == 0xD0 )
  {
    LOBYTE(v6) = 1;
    result = 0xFFFFFFD0;
    *v4 = 0xD0;
    v4 = v3 + 1;
    v8 = v3 + 2;
  }
LABEL_21:
  *v4 = v6;
  if ( a3 )
    *a3 = v4;
  *a2 = v8;
  return result;
}
// BC: using guessed type int elf_hash_bucket[17];

//----- (000006B0) --------------------------------------------------------
int __fastcall COBSDecode(int a1, unsigned __int8 **a2, const unsigned __int8 *a3, unsigned __int16 *a4)
{
  unsigned __int16 *v4; // r6
  bool v5; // zf
  int v7; // r3
  int v8; // r5
  unsigned __int8 *v9; // r1
  bool v10; // zf
  int v11; // r7
  int v12; // r10
  int v13; // r12
  int result; // r0
  bool v15; // cc

  v5 = a4 == 0;
  if ( a4 )
    v7 = *a4;
  else
    v7 = 0;
  if ( v5 )
    v4 = a4;
  v8 = 0;
  if ( !v5 )
    v4 = (unsigned __int16 *)(unsigned __int8)v7;
  v9 = *a2;
  if ( !v5 )
    v7 >>= 8;
  v10 = a1 == 0xFF;
  if ( a1 != 0xFF )
    v10 = a1 == 0xD1;
  v11 = v10;
  v12 = a1 & 0xE0;
  while ( 1 )
  {
    if ( (int)v4 > 0 )
      v13 = ((unsigned __int8)v8 ^ 1) & 1;
    else
      v13 = 0;
    if ( !v13 )
      goto LABEL_28;
    if ( v9 >= a3 )
      goto LABEL_21;
    if ( !a1 )
      break;
    v4 = (unsigned __int16 *)((char *)v4 + 0xFFFFFFFF);
    v8 = 1;
    *v9++ = a1;
LABEL_28:
    if ( v4 )
      goto LABEL_21;
    v13 = v9 < a3;
    if ( v7 <= 1 )
      v13 = 0;
    while ( v13 )
    {
      --v7;
      *v9++ = 0;
      v13 = a3 > v9;
      if ( v7 <= 1 )
        v13 = 0;
    }
    if ( v7 > 1 || v8 )
      goto LABEL_21;
    v15 = a1 <= 0;
    if ( a1 )
      v15 = v7 <= 0;
    if ( !v15 )
    {
      if ( a3 <= v9 )
      {
        LOWORD(v7) = 1;
LABEL_21:
        result = 0;
        if ( a4 )
          LOWORD(v4) = (unsigned __int16)v4 | ((_WORD)v7 << 8);
        if ( a4 )
          *a4 = (unsigned __int16)v4;
        *a2 = v9;
        return result;
      }
      *v9++ = 0;
    }
    if ( v11 || a1 == 0xD2 )
      break;
    if ( !a1 )
      goto LABEL_57;
    if ( a1 == 0xD0 )
    {
      v7 = 0;
      v4 = (_WORD *)(elf_hash_bucket + 0x13);
    }
    else if ( (a1 & 0xF0) == 0xD0 )
    {
      v7 = a1 & 0xF;
    }
    else
    {
      if ( v12 == 0xE0 )
        v7 = 2;
      else
        v4 = (unsigned __int16 *)(a1 - 1);
      if ( v12 == 0xE0 )
        v4 = (unsigned __int16 *)(a1 & 0x1F);
      else
        v7 = 1;
    }
    v8 = 1;
  }
  v9 = 0;
LABEL_57:
  if ( a4 )
    LOWORD(v13) = 0;
  result = 1;
  if ( a4 )
    *a4 = v13;
  *a2 = v9;
  return result;
}
// 714: variable 'v4' is possibly undefined
// BC: using guessed type int elf_hash_bucket[17];

//----- (00000850) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=15 queued=7 decompiled=7 lumina nreq=0 worse=0 better=0
// ALL OK, 7 function(s) have been successfully decompiled
