/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void init_proc();
int sub_1006D0();
// int __fastcall _register_frame_info(_DWORD, _DWORD); weak
// int __fastcall _cxa_finalize(void *);
// _DWORD __fastcall StartExtractWithHash(const char *, const char *, const char *, const char *, bool); idb
// int __fastcall init_array(_DWORD, _DWORD); weak
// int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD); weak
// int atexit(void (*func)(void));
// int __fastcall init_libc(_DWORD); weak
// _DWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// int __fastcall fini_array(_DWORD, _DWORD); weak
// int __fastcall preinit_array(_DWORD, _DWORD); weak
// void exit(int status);
// _DWORD __fastcall StartExtractWithHash(const char *, const char *, const char *); idb
// int printf(const char *format, ...);
// int __fastcall _deregister_frame_info(_DWORD); weak
void __noreturn btext(int a1, int a2, int a3, int a4, int a5, ...);
int sub_10089C();
int *sub_100918();
int sub_100990();
int __cdecl main(int argc, const char **argv, const char **envp);
void term_proc(void); // idb
// int __fastcall Jv_RegisterClasses(_DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

int dword_100B70 = 0; // weak
int (*off_101B74[3])() = { &sub_100918, &sub_100990, &sub_10089C }; // weak
int (*off_101B7C)() = &sub_10089C; // weak
int dword_101B80 = 0; // weak
int (*unk_101C7C)(void) = NULL; // weak
void *off_101CB8 = &__register_frame_info; // weak
void *off_101CBC = &Jv_RegisterClasses; // weak
void *off_101CC0 = &__cxa_finalize; // weak
void *off_101CC4 = &_data_start; // weak
void (__fastcall *off_101CC8)(std::ios_base::Init *__hidden this) = &std::ios_base::Init::~Init; // weak
void *off_101CCC = &__deregister_frame_info; // weak
void *_data_start = &_data_start; // weak
int errno; // weak
char byte_101CD8; // weak
_UNKNOWN unk_101CDC; // weak
_UNKNOWN unk_101CF4; // weak


//----- (001006C8) --------------------------------------------------------
void init_proc()
{
  ;
}

//----- (001006D0) --------------------------------------------------------
int sub_1006D0()
{
  return unk_101C7C();
}
// 101C7C: using guessed type int (*unk_101C7C)(void);

//----- (0010078C) --------------------------------------------------------
void __noreturn btext(int a1, int a2, int a3, int a4, int a5, ...)
{
  const char **v5; // r3
  int v7; // r0
  va_list va; // [sp+4h] [bp+4h] BYREF

  va_start(va, a5);
  v5 = &((const char **)va)[a5 + 1];
  while ( *v5++ )
    ;
  init_libc(a5);
  preinit_array(off_101B74, off_101B74);
  atexit(term_proc);
  fini_array(&off_101B7C, &dword_101B80);
  init_proc();
  init_array(off_101B74, &off_101B7C);
  errno = 0;
  v7 = main(a5, (const char **)va, &((const char **)va)[a5 + 1]);
  exit(v7);
}
// 100708: using guessed type int __fastcall init_array(_DWORD, _DWORD);
// 10072C: using guessed type int __fastcall init_libc(_DWORD);
// 100744: using guessed type int __fastcall fini_array(_DWORD, _DWORD);
// 100750: using guessed type int __fastcall preinit_array(_DWORD, _DWORD);
// 101B74: using guessed type int (*off_101B74[3])();
// 101B7C: using guessed type int (*off_101B7C)();
// 101B80: using guessed type int dword_101B80;
// 101CD4: using guessed type int errno;

//----- (0010089C) --------------------------------------------------------
int sub_10089C()
{
  int result; // r0

  if ( !byte_101CD8 )
  {
    if ( off_101CC0 )
      result = _cxa_finalize(_data_start);
    if ( off_101CCC )
      result = _deregister_frame_info(&dword_100B70);
    byte_101CD8 = 1;
  }
  return result;
}
// 100780: using guessed type int __fastcall _deregister_frame_info(_DWORD);
// 100B70: using guessed type int dword_100B70;
// 101CC0: using guessed type void *off_101CC0;
// 101CCC: using guessed type void *off_101CCC;
// 101CD0: using guessed type void *_data_start;
// 101CD8: using guessed type char byte_101CD8;

//----- (00100918) --------------------------------------------------------
int *sub_100918()
{
  int *result; // r0

  if ( off_101CB8 )
    _register_frame_info(&dword_100B70, &unk_101CDC);
  result = &dword_101B80;
  if ( dword_101B80 )
  {
    if ( off_101CBC )
      return (int *)((int (__fastcall *)(int *))off_101CBC)(&dword_101B80);
  }
  return result;
}
// 1006E4: using guessed type int __fastcall _register_frame_info(_DWORD, _DWORD);
// 100B70: using guessed type int dword_100B70;
// 101B80: using guessed type int dword_101B80;
// 101CB8: using guessed type void *off_101CB8;
// 101CBC: using guessed type void *off_101CBC;
// 104C90: using guessed type int __fastcall Jv_RegisterClasses(_DWORD);

//----- (00100990) --------------------------------------------------------
int sub_100990()
{
  std::ios_base::Init::Init((std::ios_base::Init *)&unk_101CF4);
  return _aeabi_atexit(&unk_101CF4, off_101CC8, off_101CC4);
}
// 100714: using guessed type int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD);
// 101CC4: using guessed type void *off_101CC4;
// 101CC8: using guessed type void (__fastcall *off_101CC8)(std::ios_base::Init *__hidden this);

//----- (001009D8) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int v4; // r0

  if ( (unsigned int)(argc - 4) <= 1 )
  {
    if ( argc == 4 )
      v4 = StartExtractWithHash(argv[1], argv[2], argv[3]);
    else
      v4 = StartExtractWithHash(argv[1], argv[2], argv[3], argv[4], 0);
    if ( v4 == 1 )
    {
      printf("Extraction and Hash Verification Completed\n");
      return 0;
    }
    else
    {
      printf("Extraction and Hash Verification failed\n");
      return 1;
    }
  }
  else
  {
    printf(
      "Usage: SS_HashSpeedTest <certificate File Path> <src file> <dst Dir Path> <Particular file name to be extracted [Optional]>\n");
    return 0;
  }
}

//----- (00100A80) --------------------------------------------------------
void term_proc(void)
{
  ;
}

// nfuncs=39 queued=8 decompiled=8 lumina nreq=0 worse=0 better=0
// ALL OK, 8 function(s) have been successfully decompiled
